### ISSUE TITLE
Change the Kiali-specific CRD facade based on changes for 0.1.* releases

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/kiali#11]

**Comment by jadeyliu939** [comment]
Action field ( for v 0.1.x)  included in  the latest PR : 
Kiali PR  [Kiali PR# 2815](https://github.com/kiali/kiali/pull/2815)

**Comment by jadeyliu939** [comment]
KIALI PR closed but codes were not merged, Kiali reviewers request rebase the codes and resubmit PR
